### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by Princy-patel** [Anjali1241/ProductECommerce#12]
Hi @Anjali1241 ,
I have a few suggestions for the sign-in and login page.
Can we remove the gradient color and the border, and just use a shadow? What do you think?

Please let me know your thoughts on this approach.

![image](https://github.com/user-attachments/assets/c435e5aa-ebe0-4fd7-a6cb-d25fb18f2b96)

**Comment by Anjali1241** [comment]
These are some great suggestions! @Princy-patel 
I agree that removing the gradient color and border in favor of a shadow could give the sign-in and login page a cleaner and more modern look. 

Additionally, adding an image or banner in the background could further enhance the visual appeal and make the page more engaging. Let me know if you have any specific ideas for the image or banner or I can proceed with these things

**Comment by Princy-patel** [comment]
> These are some great suggestions! @Princy-patel I agree that removing the gradient color and border in favor of a shadow could give the sign-in and login page a cleaner and more modern look.
> 
> Additionally, adding an image or banner in the background could further enhance the visual appeal and make the page more engaging. Let me know if you have any specific ideas for the image or banner or I can proceed with these things

Yes, @Anjali1241, that sounds great! Please go ahead with it. 
Let’s see how it turns out! 👍🌟

**Comment by Princy-patel** [comment]
@Anjali1241, I’ve just created below PR for a major code formatting update. Please hold off on any new changes until this PR merged to avoid significant conflicts.
If possible, could you merge this PR first?

[chore: format code with Prettier](https://github.com/Anjali1241/ProductECommerce/pull/15)
